# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns:
          - "*babel*"
          - "@pmmmwh/*"
          - "@trivago/*"
          - "@types/*"
          - "*bootstrap*"
          - "*eslint*"
          - "*postcss*"
          - "*prettier*"
          - "*stylelint*"
          - "*webpack*"
      dependencies:
        patterns:
          - "*fontawesome*"
          - "*reduxjs*"
          - "axios"
          - "browserlist"
          - "react-*"
          - "dotenv*"
          - "remark*"
          - "resolve"
          - "rss-parser"
          - "sanitize*"
          - "shelljs"
          - "styled-components"
          - "ts-node"
          - "typescript"
          - "universalify"
          - "uuid"
          - "moment"
